name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  install-wf-cli:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_SHA }}
      - name: Fetch Wayfinder CLI
        run: |
          export LOGS="$(pwd)/logs"
          export JSON_FILE="$(pwd)/env.json"
          export BIN="$(pwd)/bin"
          source ./bin/get-wf-release.sh
      - name: Save env file
        uses: actions/upload-artifact@v3
        with:
          retention-days: 2
          name: env-info-${{ inputs.cloud }}
          path: env.json
